// <auto-generated />
using System;
using EldExchange.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EldExchange.Infra.Context.Migrations
{
    [DbContext(typeof(EldDbContext))]
    [Migration("20221115060810_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("EldExchange")
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EldExchange.Domain.Models.DALs.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Complement")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses", "EldExchange");
                });

            modelBuilder.Entity("EldExchange.Domain.Models.DALs.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .IsUnicode(false)
                        .HasColumnType("char(18)")
                        .IsFixedLength();

                    b.Property<bool>("IsWorking")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Agencies", "EldExchange");
                });

            modelBuilder.Entity("EldExchange.Domain.Models.DALs.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Currencies", "EldExchange");

                    b.HasData(
                        new
                        {
                            Code = "AED",
                            Country = "UNITED ARAB EMIRATES (THE)",
                            Name = "UAE Dirham",
                            Number = 784
                        },
                        new
                        {
                            Code = "AFN",
                            Country = "AFGHANISTAN",
                            Name = "Afghani",
                            Number = 971
                        },
                        new
                        {
                            Code = "ALL",
                            Country = "ALBANIA",
                            Name = "Lek",
                            Number = 8
                        },
                        new
                        {
                            Code = "AMD",
                            Country = "ARMENIA",
                            Name = "Armenian Dram",
                            Number = 51
                        },
                        new
                        {
                            Code = "ANG",
                            Country = "CURAÇAO",
                            Name = "Netherlands Antillean Guilder",
                            Number = 532
                        },
                        new
                        {
                            Code = "AOA",
                            Country = "ANGOLA",
                            Name = "Kwanza",
                            Number = 973
                        },
                        new
                        {
                            Code = "ARS",
                            Country = "ARGENTINA",
                            Name = "Argentine Peso",
                            Number = 32
                        },
                        new
                        {
                            Code = "AUD",
                            Country = "AUSTRALIA",
                            Name = "Australian Dollar",
                            Number = 36
                        },
                        new
                        {
                            Code = "AWG",
                            Country = "ARUBA",
                            Name = "Aruban Florin",
                            Number = 533
                        },
                        new
                        {
                            Code = "AZN",
                            Country = "AZERBAIJAN",
                            Name = "Azerbaijanian Manat",
                            Number = 944
                        },
                        new
                        {
                            Code = "BAM",
                            Country = "BOSNIA AND HERZEGOVINA",
                            Name = "Convertible Mark",
                            Number = 977
                        },
                        new
                        {
                            Code = "BBD",
                            Country = "BARBADOS",
                            Name = "Barbados Dollar",
                            Number = 52
                        },
                        new
                        {
                            Code = "BDT",
                            Country = "BANGLADESH",
                            Name = "Taka",
                            Number = 50
                        },
                        new
                        {
                            Code = "BGN",
                            Country = "BULGARIA",
                            Name = "Bulgarian Lev",
                            Number = 975
                        },
                        new
                        {
                            Code = "BHD",
                            Country = "BAHRAIN",
                            Name = "Bahraini Dinar",
                            Number = 48
                        },
                        new
                        {
                            Code = "BIF",
                            Country = "BURUNDI",
                            Name = "Burundi Franc",
                            Number = 108
                        },
                        new
                        {
                            Code = "BMD",
                            Country = "BERMUDA",
                            Name = "Bermudian Dollar",
                            Number = 60
                        },
                        new
                        {
                            Code = "BND",
                            Country = "BRUNEI DARUSSALAM",
                            Name = "Brunei Dollar",
                            Number = 96
                        },
                        new
                        {
                            Code = "BOB",
                            Country = "BOLIVIA (PLURINATIONAL STATE    OF)",
                            Name = "Boliviano",
                            Number = 68
                        },
                        new
                        {
                            Code = "BOV",
                            Country = "BOLIVIA (PLURINATIONAL STATE    OF)",
                            Name = "Mvdol",
                            Number = 984
                        },
                        new
                        {
                            Code = "BRL",
                            Country = "BRAZIL",
                            Name = "Brazilian Real",
                            Number = 986
                        },
                        new
                        {
                            Code = "BSD",
                            Country = "BAHAMAS (THE)",
                            Name = "Bahamian Dollar",
                            Number = 44
                        },
                        new
                        {
                            Code = "BTN",
                            Country = "BHUTAN",
                            Name = "Ngultrum",
                            Number = 64
                        },
                        new
                        {
                            Code = "BWP",
                            Country = "BOTSWANA",
                            Name = "Pula",
                            Number = 72
                        },
                        new
                        {
                            Code = "BYN",
                            Country = "BELARUS",
                            Name = "Belarussian Ruble",
                            Number = 933
                        },
                        new
                        {
                            Code = "BZD",
                            Country = "BELIZE",
                            Name = "Belize Dollar",
                            Number = 84
                        },
                        new
                        {
                            Code = "CAD",
                            Country = "CANADA",
                            Name = "Canadian Dollar",
                            Number = 124
                        },
                        new
                        {
                            Code = "CDF",
                            Country = "CONGO (THE DEMOCRATIC    REPUBLIC OF THE)",
                            Name = "Congolese Franc",
                            Number = 976
                        },
                        new
                        {
                            Code = "CHE",
                            Country = "SWITZERLAND",
                            Name = "WIR Euro",
                            Number = 947
                        },
                        new
                        {
                            Code = "CHF",
                            Country = "LIECHTENSTEIN",
                            Name = "Swiss Franc",
                            Number = 756
                        },
                        new
                        {
                            Code = "CHW",
                            Country = "SWITZERLAND",
                            Name = "WIR Franc",
                            Number = 948
                        },
                        new
                        {
                            Code = "CLF",
                            Country = "CHILE",
                            Name = "Unidad de Fomento",
                            Number = 990
                        },
                        new
                        {
                            Code = "CLP",
                            Country = "CHILE",
                            Name = "Chilean Peso",
                            Number = 152
                        },
                        new
                        {
                            Code = "CNY",
                            Country = "CHINA",
                            Name = "Yuan Renminbi",
                            Number = 156
                        },
                        new
                        {
                            Code = "COP",
                            Country = "COLOMBIA",
                            Name = "Colombian Peso",
                            Number = 170
                        },
                        new
                        {
                            Code = "COU",
                            Country = "COLOMBIA",
                            Name = "Unidad de Valor Real",
                            Number = 970
                        },
                        new
                        {
                            Code = "CRC",
                            Country = "COSTA RICA",
                            Name = "Costa Rican Colon",
                            Number = 188
                        },
                        new
                        {
                            Code = "CUC",
                            Country = "CUBA",
                            Name = "Peso Convertible",
                            Number = 931
                        },
                        new
                        {
                            Code = "CUP",
                            Country = "CUBA",
                            Name = "Cuban Peso",
                            Number = 192
                        },
                        new
                        {
                            Code = "CVE",
                            Country = "CABO VERDE",
                            Name = "Cabo Verde Escudo",
                            Number = 132
                        },
                        new
                        {
                            Code = "CZK",
                            Country = "CZECH REPUBLIC (THE)",
                            Name = "Czech Koruna",
                            Number = 203
                        },
                        new
                        {
                            Code = "DJF",
                            Country = "DJIBOUTI",
                            Name = "Djibouti Franc",
                            Number = 262
                        },
                        new
                        {
                            Code = "DKK",
                            Country = "DENMARK",
                            Name = "Danish Krone",
                            Number = 208
                        },
                        new
                        {
                            Code = "DOP",
                            Country = "DOMINICAN REPUBLIC (THE)",
                            Name = "Dominican Peso",
                            Number = 214
                        },
                        new
                        {
                            Code = "DZD",
                            Country = "ALGERIA",
                            Name = "Algerian Dinar",
                            Number = 12
                        },
                        new
                        {
                            Code = "EGP",
                            Country = "EGYPT",
                            Name = "Egyptian Pound",
                            Number = 818
                        },
                        new
                        {
                            Code = "ERN",
                            Country = "ERITREA",
                            Name = "Nakfa",
                            Number = 232
                        },
                        new
                        {
                            Code = "ETB",
                            Country = "ETHIOPIA",
                            Name = "Ethiopian Birr",
                            Number = 230
                        },
                        new
                        {
                            Code = "EUR",
                            Country = "ÅLAND ISLANDS",
                            Name = "Euro",
                            Number = 978
                        },
                        new
                        {
                            Code = "FJD",
                            Country = "FIJI",
                            Name = "Fiji Dollar",
                            Number = 242
                        },
                        new
                        {
                            Code = "FKP",
                            Country = "FALKLAND ISLANDS (THE)    [MALVINAS]",
                            Name = "Falkland Islands Pound",
                            Number = 238
                        },
                        new
                        {
                            Code = "GBP",
                            Country = "GUERNSEY",
                            Name = "Pound Sterling",
                            Number = 826
                        },
                        new
                        {
                            Code = "GEL",
                            Country = "GEORGIA",
                            Name = "Lari",
                            Number = 981
                        },
                        new
                        {
                            Code = "GHS",
                            Country = "GHANA",
                            Name = "Ghana Cedi",
                            Number = 936
                        },
                        new
                        {
                            Code = "GIP",
                            Country = "GIBRALTAR",
                            Name = "Gibraltar Pound",
                            Number = 292
                        },
                        new
                        {
                            Code = "GMD",
                            Country = "GAMBIA (THE)",
                            Name = "Dalasi",
                            Number = 270
                        },
                        new
                        {
                            Code = "GNF",
                            Country = "GUINEA",
                            Name = "Guinea Franc",
                            Number = 324
                        },
                        new
                        {
                            Code = "GTQ",
                            Country = "GUATEMALA",
                            Name = "Quetzal",
                            Number = 320
                        },
                        new
                        {
                            Code = "GYD",
                            Country = "GUYANA",
                            Name = "Guyana Dollar",
                            Number = 328
                        },
                        new
                        {
                            Code = "HKD",
                            Country = "HONG KONG",
                            Name = "Hong Kong Dollar",
                            Number = 344
                        },
                        new
                        {
                            Code = "HNL",
                            Country = "HONDURAS",
                            Name = "Lempira",
                            Number = 340
                        },
                        new
                        {
                            Code = "HRK",
                            Country = "CROATIA",
                            Name = "Kuna",
                            Number = 191
                        },
                        new
                        {
                            Code = "HTG",
                            Country = "HAITI",
                            Name = "Gourde",
                            Number = 332
                        },
                        new
                        {
                            Code = "HUF",
                            Country = "HUNGARY",
                            Name = "Forint",
                            Number = 348
                        },
                        new
                        {
                            Code = "IDR",
                            Country = "INDONESIA",
                            Name = "Rupiah",
                            Number = 360
                        },
                        new
                        {
                            Code = "ILS",
                            Country = "ISRAEL",
                            Name = "New Israeli Sheqel",
                            Number = 376
                        },
                        new
                        {
                            Code = "INR",
                            Country = "BHUTAN",
                            Name = "Indian Rupee",
                            Number = 356
                        },
                        new
                        {
                            Code = "IQD",
                            Country = "IRAQ",
                            Name = "Iraqi Dinar",
                            Number = 368
                        },
                        new
                        {
                            Code = "IRR",
                            Country = "IRAN (ISLAMIC REPUBLIC OF)",
                            Name = "Iranian Rial",
                            Number = 364
                        },
                        new
                        {
                            Code = "ISK",
                            Country = "ICELAND",
                            Name = "Iceland Krona",
                            Number = 352
                        },
                        new
                        {
                            Code = "JMD",
                            Country = "JAMAICA",
                            Name = "Jamaican Dollar",
                            Number = 388
                        },
                        new
                        {
                            Code = "JOD",
                            Country = "JORDAN",
                            Name = "Jordanian Dinar",
                            Number = 400
                        },
                        new
                        {
                            Code = "JPY",
                            Country = "JAPAN",
                            Name = "Yen",
                            Number = 392
                        },
                        new
                        {
                            Code = "KES",
                            Country = "KENYA",
                            Name = "Kenyan Shilling",
                            Number = 404
                        },
                        new
                        {
                            Code = "KGS",
                            Country = "KYRGYZSTAN",
                            Name = "Som",
                            Number = 417
                        },
                        new
                        {
                            Code = "KHR",
                            Country = "CAMBODIA",
                            Name = "Riel",
                            Number = 116
                        },
                        new
                        {
                            Code = "KMF",
                            Country = "COMOROS (THE)",
                            Name = "Comoro Franc",
                            Number = 174
                        },
                        new
                        {
                            Code = "KPW",
                            Country = "KOREA (THE DEMOCRATIC    PEOPLE’S REPUBLIC OF)",
                            Name = "North Korean Won",
                            Number = 408
                        },
                        new
                        {
                            Code = "KRW",
                            Country = "KOREA (THE REPUBLIC OF)",
                            Name = "Won",
                            Number = 410
                        },
                        new
                        {
                            Code = "KWD",
                            Country = "KUWAIT",
                            Name = "Kuwaiti Dinar",
                            Number = 414
                        },
                        new
                        {
                            Code = "KYD",
                            Country = "CAYMAN ISLANDS (THE)",
                            Name = "Cayman Islands Dollar",
                            Number = 136
                        },
                        new
                        {
                            Code = "KZT",
                            Country = "KAZAKHSTAN",
                            Name = "Tenge",
                            Number = 398
                        },
                        new
                        {
                            Code = "LAK",
                            Country = "LAO PEOPLE’S DEMOCRATIC    REPUBLIC (THE)",
                            Name = "Kip",
                            Number = 418
                        },
                        new
                        {
                            Code = "LBP",
                            Country = "LEBANON",
                            Name = "Lebanese Pound",
                            Number = 422
                        },
                        new
                        {
                            Code = "LKR",
                            Country = "SRI LANKA",
                            Name = "Sri Lanka Rupee",
                            Number = 144
                        },
                        new
                        {
                            Code = "LRD",
                            Country = "LIBERIA",
                            Name = "Liberian Dollar",
                            Number = 430
                        },
                        new
                        {
                            Code = "LSL",
                            Country = "LESOTHO",
                            Name = "Loti",
                            Number = 426
                        },
                        new
                        {
                            Code = "LYD",
                            Country = "LIBYA",
                            Name = "Libyan Dinar",
                            Number = 434
                        },
                        new
                        {
                            Code = "MAD",
                            Country = "MOROCCO",
                            Name = "Moroccan Dirham",
                            Number = 504
                        },
                        new
                        {
                            Code = "MDL",
                            Country = "MOLDOVA (THE REPUBLIC OF)",
                            Name = "Moldovan Leu",
                            Number = 498
                        },
                        new
                        {
                            Code = "MGA",
                            Country = "MADAGASCAR",
                            Name = "Malagasy Ariary",
                            Number = 969
                        },
                        new
                        {
                            Code = "MKD",
                            Country = "REPUBLIC OF NORTH MACEDONIA",
                            Name = "Denar",
                            Number = 807
                        },
                        new
                        {
                            Code = "MMK",
                            Country = "MYANMAR",
                            Name = "Kyat",
                            Number = 104
                        },
                        new
                        {
                            Code = "MNT",
                            Country = "MONGOLIA",
                            Name = "Tugrik",
                            Number = 496
                        },
                        new
                        {
                            Code = "MOP",
                            Country = "MACAO",
                            Name = "Pataca",
                            Number = 446
                        },
                        new
                        {
                            Code = "MRU",
                            Country = "MAURITANIA",
                            Name = "Ouguiya",
                            Number = 929
                        },
                        new
                        {
                            Code = "MUR",
                            Country = "MAURITIUS",
                            Name = "Mauritius Rupee",
                            Number = 480
                        },
                        new
                        {
                            Code = "MVR",
                            Country = "MALDIVES",
                            Name = "Rufiyaa",
                            Number = 462
                        },
                        new
                        {
                            Code = "MWK",
                            Country = "MALAWI",
                            Name = "Kwacha",
                            Number = 454
                        },
                        new
                        {
                            Code = "MXN",
                            Country = "MEXICO",
                            Name = "Mexican Peso",
                            Number = 484
                        },
                        new
                        {
                            Code = "MXV",
                            Country = "MEXICO",
                            Name = "Mexican Unidad de Inversion (UDI)",
                            Number = 979
                        },
                        new
                        {
                            Code = "MYR",
                            Country = "MALAYSIA",
                            Name = "Malaysian Ringgit",
                            Number = 458
                        },
                        new
                        {
                            Code = "MZN",
                            Country = "MOZAMBIQUE",
                            Name = "Mozambique Metical",
                            Number = 943
                        },
                        new
                        {
                            Code = "NAD",
                            Country = "NAMIBIA",
                            Name = "Namibia Dollar",
                            Number = 516
                        },
                        new
                        {
                            Code = "NGN",
                            Country = "NIGERIA",
                            Name = "Naira",
                            Number = 566
                        },
                        new
                        {
                            Code = "NIO",
                            Country = "NICARAGUA",
                            Name = "Cordoba Oro",
                            Number = 558
                        },
                        new
                        {
                            Code = "NOK",
                            Country = "BOUVET ISLAND",
                            Name = "Norwegian Krone",
                            Number = 578
                        },
                        new
                        {
                            Code = "NPR",
                            Country = "NEPAL",
                            Name = "Nepalese Rupee",
                            Number = 524
                        },
                        new
                        {
                            Code = "NZD",
                            Country = "COOK ISLANDS (THE)",
                            Name = "New Zealand Dollar",
                            Number = 554
                        },
                        new
                        {
                            Code = "OMR",
                            Country = "OMAN",
                            Name = "Rial Omani",
                            Number = 512
                        },
                        new
                        {
                            Code = "PAB",
                            Country = "PANAMA",
                            Name = "Balboa",
                            Number = 590
                        },
                        new
                        {
                            Code = "PEN",
                            Country = "PERU",
                            Name = "Nuevo Sol",
                            Number = 604
                        },
                        new
                        {
                            Code = "PGK",
                            Country = "PAPUA NEW GUINEA",
                            Name = "Kina",
                            Number = 598
                        },
                        new
                        {
                            Code = "PHP",
                            Country = "PHILIPPINES (THE)",
                            Name = "Philippine Peso",
                            Number = 608
                        },
                        new
                        {
                            Code = "PKR",
                            Country = "PAKISTAN",
                            Name = "Pakistan Rupee",
                            Number = 586
                        },
                        new
                        {
                            Code = "PLN",
                            Country = "POLAND",
                            Name = "Zloty",
                            Number = 985
                        },
                        new
                        {
                            Code = "PYG",
                            Country = "PARAGUAY",
                            Name = "Guarani",
                            Number = 600
                        },
                        new
                        {
                            Code = "QAR",
                            Country = "QATAR",
                            Name = "Qatari Rial",
                            Number = 634
                        },
                        new
                        {
                            Code = "RON",
                            Country = "ROMANIA",
                            Name = "Romanian Leu",
                            Number = 946
                        },
                        new
                        {
                            Code = "RSD",
                            Country = "SERBIA",
                            Name = "Serbian Dinar",
                            Number = 941
                        },
                        new
                        {
                            Code = "RUB",
                            Country = "RUSSIAN FEDERATION (THE)",
                            Name = "Russian Ruble",
                            Number = 643
                        },
                        new
                        {
                            Code = "RWF",
                            Country = "RWANDA",
                            Name = "Rwanda Franc",
                            Number = 646
                        },
                        new
                        {
                            Code = "SAR",
                            Country = "SAUDI ARABIA",
                            Name = "Saudi Riyal",
                            Number = 682
                        },
                        new
                        {
                            Code = "SBD",
                            Country = "SOLOMON ISLANDS",
                            Name = "Solomon Islands Dollar",
                            Number = 90
                        },
                        new
                        {
                            Code = "SCR",
                            Country = "SEYCHELLES",
                            Name = "Seychelles Rupee",
                            Number = 690
                        },
                        new
                        {
                            Code = "SDG",
                            Country = "SUDAN (THE)",
                            Name = "Sudanese Pound",
                            Number = 938
                        },
                        new
                        {
                            Code = "SEK",
                            Country = "SWEDEN",
                            Name = "Swedish Krona",
                            Number = 752
                        },
                        new
                        {
                            Code = "SGD",
                            Country = "SINGAPORE",
                            Name = "Singapore Dollar",
                            Number = 702
                        },
                        new
                        {
                            Code = "SHP",
                            Country = "SAINT HELENA, ASCENSION AND    TRISTAN DA CUNHA",
                            Name = "Saint Helena Pound",
                            Number = 654
                        },
                        new
                        {
                            Code = "SLE",
                            Country = "SIERRA LEONE",
                            Name = "Leone",
                            Number = 925
                        },
                        new
                        {
                            Code = "SOS",
                            Country = "SOMALIA",
                            Name = "Somali Shilling",
                            Number = 706
                        },
                        new
                        {
                            Code = "SRD",
                            Country = "SURINAME",
                            Name = "Surinam Dollar",
                            Number = 968
                        },
                        new
                        {
                            Code = "SSP",
                            Country = "SOUTH SUDAN",
                            Name = "South Sudanese Pound",
                            Number = 728
                        },
                        new
                        {
                            Code = "STN",
                            Country = "SAO TOME AND PRINCIPE",
                            Name = "Dobra",
                            Number = 930
                        },
                        new
                        {
                            Code = "SVC",
                            Country = "EL SALVADOR",
                            Name = "El Salvador Colon",
                            Number = 222
                        },
                        new
                        {
                            Code = "SYP",
                            Country = "SYRIAN ARAB REPUBLIC",
                            Name = "Syrian Pound",
                            Number = 760
                        },
                        new
                        {
                            Code = "SZL",
                            Country = "SWAZILAND",
                            Name = "Lilangeni",
                            Number = 748
                        },
                        new
                        {
                            Code = "THB",
                            Country = "THAILAND",
                            Name = "Baht",
                            Number = 764
                        },
                        new
                        {
                            Code = "TJS",
                            Country = "TAJIKISTAN",
                            Name = "Somoni",
                            Number = 972
                        },
                        new
                        {
                            Code = "TMT",
                            Country = "TURKMENISTAN",
                            Name = "Turkmenistan New Manat",
                            Number = 934
                        },
                        new
                        {
                            Code = "TND",
                            Country = "TUNISIA",
                            Name = "Tunisian Dinar",
                            Number = 788
                        },
                        new
                        {
                            Code = "TOP",
                            Country = "TONGA",
                            Name = "Pa’anga",
                            Number = 776
                        },
                        new
                        {
                            Code = "TRY",
                            Country = "TURKEY",
                            Name = "Turkish Lira",
                            Number = 949
                        },
                        new
                        {
                            Code = "TTD",
                            Country = "TRINIDAD AND TOBAGO",
                            Name = "Trinidad and Tobago Dollar",
                            Number = 780
                        },
                        new
                        {
                            Code = "TWD",
                            Country = "TAIWAN (PROVINCE OF CHINA)",
                            Name = "New Taiwan Dollar",
                            Number = 901
                        },
                        new
                        {
                            Code = "TZS",
                            Country = "TANZANIA, UNITED REPUBLIC OF",
                            Name = "Tanzanian Shilling",
                            Number = 834
                        },
                        new
                        {
                            Code = "UAH",
                            Country = "UKRAINE",
                            Name = "Hryvnia",
                            Number = 980
                        },
                        new
                        {
                            Code = "UGX",
                            Country = "UGANDA",
                            Name = "Uganda Shilling",
                            Number = 800
                        },
                        new
                        {
                            Code = "USD",
                            Country = "AMERICAN SAMOA",
                            Name = "US Dollar",
                            Number = 840
                        },
                        new
                        {
                            Code = "USN",
                            Country = "UNITED STATES OF AMERICA    (THE)",
                            Name = "US Dollar (Next day)",
                            Number = 997
                        },
                        new
                        {
                            Code = "UYI",
                            Country = "URUGUAY",
                            Name = "Uruguay Peso en Unidades Indexadas (URUIURUI)",
                            Number = 940
                        },
                        new
                        {
                            Code = "UYU",
                            Country = "URUGUAY",
                            Name = "Peso Uruguayo",
                            Number = 858
                        },
                        new
                        {
                            Code = "UZS",
                            Country = "UZBEKISTAN",
                            Name = "Uzbekistan Sum",
                            Number = 860
                        },
                        new
                        {
                            Code = "VED",
                            Country = "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
                            Name = "Bolivar",
                            Number = 926
                        },
                        new
                        {
                            Code = "VEF",
                            Country = "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
                            Name = "Bolivar",
                            Number = 937
                        },
                        new
                        {
                            Code = "VND",
                            Country = "VIET NAM",
                            Name = "Dong",
                            Number = 704
                        },
                        new
                        {
                            Code = "VUV",
                            Country = "VANUATU",
                            Name = "Vatu",
                            Number = 548
                        },
                        new
                        {
                            Code = "WST",
                            Country = "SAMOA",
                            Name = "Tala",
                            Number = 882
                        },
                        new
                        {
                            Code = "XAF",
                            Country = "CAMEROON",
                            Name = "CFA Franc BEAC",
                            Number = 950
                        },
                        new
                        {
                            Code = "XCD",
                            Country = "ANGUILLA",
                            Name = "East Caribbean Dollar",
                            Number = 951
                        },
                        new
                        {
                            Code = "XDR",
                            Country = "INTERNATIONAL MONETARY FUND    (IMF)",
                            Name = "SDR (Special Drawing Right)",
                            Number = 960
                        },
                        new
                        {
                            Code = "XOF",
                            Country = "BENIN",
                            Name = "CFA Franc BCEAO",
                            Number = 952
                        },
                        new
                        {
                            Code = "XPF",
                            Country = "FRENCH POLYNESIA",
                            Name = "CFP Franc",
                            Number = 953
                        },
                        new
                        {
                            Code = "XSU",
                            Country = "SISTEMA UNITARIO DE    COMPENSACION REGIONAL DE PAGOS \"SUCRE\"",
                            Name = "Sucre",
                            Number = 994
                        },
                        new
                        {
                            Code = "XUA",
                            Country = "MEMBER COUNTRIES OF THE    AFRICAN DEVELOPMENT BANK GROUP",
                            Name = "ADB Unit of Account",
                            Number = 965
                        },
                        new
                        {
                            Code = "YER",
                            Country = "YEMEN",
                            Name = "Yemeni Rial",
                            Number = 886
                        },
                        new
                        {
                            Code = "ZAR",
                            Country = "LESOTHO",
                            Name = "Rand",
                            Number = 710
                        },
                        new
                        {
                            Code = "ZMW",
                            Country = "ZAMBIA",
                            Name = "Zambian Kwacha",
                            Number = 967
                        },
                        new
                        {
                            Code = "ZWL",
                            Country = "ZIMBABWE",
                            Name = "Zimbabwe Dollar",
                            Number = 932
                        });
                });

            modelBuilder.Entity("EldExchange.Domain.Models.DALs.Money", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Coin");

                    b.HasKey("Code", "Value", "Type");

                    b.ToTable("Money", "EldExchange");

                    b.HasDiscriminator<string>("Type").HasValue("Money");
                });

            modelBuilder.Entity("EldExchange.Domain.Models.DALs.Telephone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("Number", "RegionCode", "CountryCode")
                        .IsUnique()
                        .HasFilter("[RegionCode] IS NOT NULL");

                    b.ToTable("Telephones", "EldExchange");
                });

            modelBuilder.Entity("EldExchange.Domain.Models.DALs.BankNote", b =>
                {
                    b.HasBaseType("EldExchange.Domain.Models.DALs.Money");

                    b.HasDiscriminator().HasValue("BankNote");

                    b.HasData(
                        new
                        {
                            Code = "USD",
                            Value = 1m,
                            Type = "BankNote"
                        });
                });

            modelBuilder.Entity("EldExchange.Domain.Models.DALs.Coin", b =>
                {
                    b.HasBaseType("EldExchange.Domain.Models.DALs.Money");

                    b.HasDiscriminator().HasValue("Coin");

                    b.HasData(
                        new
                        {
                            Code = "USD",
                            Value = 1m,
                            Type = "Coin"
                        });
                });

            modelBuilder.Entity("EldExchange.Domain.Models.DALs.Address", b =>
                {
                    b.HasOne("EldExchange.Domain.Models.DALs.Agency", null)
                        .WithOne("Address")
                        .HasForeignKey("EldExchange.Domain.Models.DALs.Address", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EldExchange.Domain.Models.DALs.Money", b =>
                {
                    b.HasOne("EldExchange.Domain.Models.DALs.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("EldExchange.Domain.Models.DALs.Telephone", b =>
                {
                    b.HasOne("EldExchange.Domain.Models.DALs.Agency", null)
                        .WithMany("Phones")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EldExchange.Domain.Models.DALs.Agency", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
